properties = ['text', 'orientation',
              'source', 'halign',
              "background_color",
              'spacing', 'width',
              'height', 'min_width',
              'min_height', 'title',
              'hidden', 'fullscreen',
              'minimize', 'maximize',
              'frameless', 'app_icon',
              'icon', 'source',
              'x', 'y', 'styles',
              'text_align', 'radius',
              'radius_x', 'radius_y', 'margin', 'capitalize',
              'style', 'pos', 'size', 'opacity',
              'line_points', 'name', 'id',
              'color', "font_family", "font_weight",
              'font_size', "italic"]